Add Flutter snap path to getKnownFlutterSdkPaths()
flutter/flutter-intellij pull request #5123
Opened 2020-12-16 13:10 UTC by MarcusTomlinson

Fixes the second half of https://github.com/canonical/flutter-snap/issues/19.

Changes proposed in this pull request:

* If present, add the Flutter snap SDK path to the list returned from getKnownFlutterSdkPaths()
  * This path is well-known and standard on all Linux platforms.

2020-12-16 16:00 UTC, devoncarew requested changes
Thanks for the contribution! One comment on the PR, in-line.

2020-12-16 16:18 UTC, MarcusTomlinson commented on src/io/flutter/sdk/FlutterSdkUtil.java
> +    final File snapSdkPath = new File(System.getenv("HOME") + "/snap/flutter/common/flutter");
Ah yes, much cleaner. Done :)

2020-12-16 16:51 UTC, devoncarew approved these changes
Thanks!

2020-12-16 16:51 UTC, merged

2021-01-26 18:18 UTC, stevemessick commented
@MarcusTomlinson Could you submit a PR that updates the AUTHORS file with your name and email? I'm working on the release notes for the version we're publishing this Friday and would like to give your credit for your contribution.

2021-01-26 18:26 UTC, MarcusTomlinson commented
> @MarcusTomlinson Could you submit a PR that updates the AUTHORS file with your name and email? I'm working on the release notes for the version we're publishing this Friday and would like to give your credit for your contribution.

Absolutely :) Will do so in a few.

2021-01-26 18:40 UTC, stevemessick commented
Also, if you have a screen shot to illustrate the feature I'd be happy to include it. I don't have Linux handy.